### ISSUE TITLE
Can't deploy UpgradeAgent to private net

### ISSUE THREAD

**Issue by in10se** [Lunyr/crowdsale-contracts#6]
I'm trying to deploy the Lunyr contracts to my own private net run by geth. For some reason, it always fails to deploy the UpgradeAgent contract like this:

> Running migration: 1_initial_migration.js
>   Replacing Migrations...
>   Migrations: 0x5efe2139a070a13874024cb6c7201d9d6a18943b
> Saving successful migration to network...
> Saving artifacts...
> Running migration: 2_deploy_contracts.js
>   Deploying MultiSigWallet...
>   MultiSigWallet: 0xa79ad6b883af9338255d08b1b3bf952a5867419e
>   Deploying LunyrToken...
>   LunyrToken: 0x0bbd2736747791b50c94d2d8b26ae2cf6f3f86eb
> Agent owner: 0x511b066674dc319a5c4aa8eb31dcc40d2ceb6813
> Token address: 0x0bbd2736747791b50c94d2d8b26ae2cf6f3f86eb
> Gas: 896254
>   Deploying UpgradeAgent...
> Error encountered, bailing. Network state unknown. Review successful transactions manually.
> Error: The contract code couldn't be stored, please check your gas amount.
>     at Object.callback (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/contract.js:147:46)
>     at /usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/method.js:142:25
>     at /usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/requestmanager.js:89:9

No matter how much gas I'm willing to provide (gasEstimate), it always fails either by this error or by reaching the gas limit. Interestingly, you have this piece of code commented out:
```
    //   functionData = utils.getFunctionEncoding('UpgradeAgent(address)',[token.address]);
    //   return web3.eth.estimateGas({data:functionData});
    // }).then(function(gasEstimate){
    //   console.log(gasEstimate);
```
If I uncomment it, it seems to work but after 50 blocks mined I get an error saying that the transaction couldn't be found. Also, the gasEstimate that it finds is 50,000,000, compared to the 2,000,000 which is hard coded now.

Any ideas why this might happen?

**Comment by in10se** [comment]
I found the bug. For some unknown reason, the _UpgradeAgent_ artifacts has _binary_unlinked = "0x"_ which means that the transaction that needs to create the contract is sent with _data = "0x"_. Obviously, the transaction is bound to fail but the error complains about gas, rather than the lack of data. I solved this by deleting the whole build folder. After running _truffle compile_, I was able to successfully deploy all the contracts.
